In [34]:
# -------------------------------------------
# 1. IMPORT LIBRARIES
# -------------------------------------------
import pandas as pd
import numpy as np

# For label encoding
from sklearn.preprocessing import LabelEncoder

# For train-test split
from sklearn.model_selection import train_test_split

# -------------------------------------------
# 2. LOAD DATASET
# -------------------------------------------

file_path = r"C:\Users\HP\Desktop\FuWukari\Eating Disorder\Dataset.csv"
df = pd.read_csv(file_path)

print("=== BEFORE PREPROCESSING: SAMPLE ROWS ===")
display(df.head())

print("\n=== BEFORE PREPROCESSING: INFO ===")
display(df.info())

print("\n=== BEFORE PREPROCESSING: MISSING VALUES ===")
display(df.isnull().sum())

=== BEFORE PREPROCESSING: SAMPLE ROWS ===

,Age_Range,Gender,Division_ofOrigin,Current_EducationLevel,Employment_Status,Marital_Status,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,...,Days_TriedLimitFoodToControlShapeOrWeight,Days_FastedToControlShapeOrWeight,Days_ExcludedFoodToControlShapeOrWeight,Days_FollowedRulesToControlShapeOrWeight,Days_FearLosingControlOverEating,Eat_SpecificFoodsHabitually,Location_TriggersHabitualEating,AutomaticEating_WhenExperiencingStrongEmotion,Realize_AfterEatingOutOfHabit,Perception_EatingDisorder
0,18-24,Male,Rajshahi,Bachelor's degree 3rd year,Student,In a relationship,Often,Never,Sometimes,Sometimes,...,13-27 days,Every day,1-12 days,Every day,1-12 days,Often,Often,Sometimes,Never,"Yes, I believe I do"
1,25-34,Female,Chattogram,Master's degree 2nd year,Self-employed,Married,Often,Often,Seldom,Often,...,1-12 days,13-27 days,13-27 days,No days,13-27 days,Often,Sometimes,Never,Never,"Yes, I believe I do"
2,18-24,Male,Khulna,Bachelor's degree 2nd year,Student,Single,Often,Never,Often,Seldom,...,Every day,1-12 days,1-12 days,13-27 days,1-12 days,Never,Sometimes,Never,Never,"Yes, I believe I do"
3,18-24,Female,Dhaka,Bachelor's degree 2nd year,Self-employed,Married,Often,Often,Never,Sometimes,...,Every day,1-12 days,Every day,1-12 days,1-12 days,Sometimes,Often,Often,Often,"Yes, I believe I do"
4,18-24,Male,Sylhet,Bachelor's degree 3rd year,Student,Single,Sometimes,Never,Seldom,Often,...,1-12 days,13-27 days,1-12 days,1-12 days,1-12 days,Often,Often,Seldom,Often,"Yes, I believe I do"

=== BEFORE PREPROCESSING: INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 57 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age_Range                                      550 non-null    object
 1   Gender                                         550 non-null    object
 2   Division_ofOrigin                              550 non-null    object
 3   Current_EducationLevel                         550 non-null    object
 4   Employment_Status                              550 non-null    object
 5   Marital_Status                                 550 non-null    object
 6   EatLess_OnWeightGain                           550 non-null    object
 7   EatLess_AtMealtime                             550 non-null    object
 8   RefuseFood_WeightConcern                       550 non-null    object
 9   Monitor_Food                                   550 non-null    object
 10  Eat_SlimmingFoods                              550 non-null    object
 11  EatLess_AfterOvereating                        550 non-null    object
 12  EatLess_ToPreventWeightGain                    550 non-null    object
 13  AvoidSnacks_BetweenMealsForWeightConcern       550 non-null    object
 14  AvoidEveningEating_ForWeightConcern            550 non-null    object
 15  ConsiderWeight_WhenEating                      550 non-null    object
 16  Eat_WhenIrritated                              550 non-null    object
 17  Eat_WhenUnoccupied                             550 non-null    object
 18  Eat_WhenDepressedOrDiscouraged                 550 non-null    object
 19  Eat_WhenLonely                                 550 non-null    object
 20  Eat_WhenSomeoneLetYouDown                      550 non-null    object
 21  Eat_WhenAngry                                  550 non-null    object
 22  Eat_WhenExpectingBad                           550 non-null    object
 23  Eat_WhenAnxious                                550 non-null    object
 24  Eat_WhenThingsGoWrong                          550 non-null    object
 25  Eat_WhenFrightened                             550 non-null    object
 26  Eat_WhenDisappointed                           550 non-null    object
 27  Eat_WhenEmotionallyUpset                       550 non-null    object
 28  Eat_WhenBoredOrRestless                        550 non-null    object
 29  EatMore_IfFoodTasty                            550 non-null    object
 30  EatMore_IfFoodSmellsOrLooksGood                550 non-null    object
 31  Eat_WhenSeeDeliciousFood                       550 non-null    object
 32  Eat_DeliciousFoodImmediately                   550 non-null    object
 33  DesireToBuy_FromBakery                         550 non-null    object
 34  DesireToBuy _FromSnackBarOrCafe                550 non-null    object
 35  DesireToEat_WhenSeeOthersEating                550 non-null    object
 36  Resist_DeliciousFood                           550 non-null    object
 37  EatMore_WhenSeeOthersEating                    550 non-null    object
 38  Eat_WhenPreparingMeal                          550 non-null    object
 39  Days_DesireForFlatStomach                      550 non-null    object
 40  Days_FeltFat                                   550 non-null    object
 41  Days_WeightAffectedSelfJudgment                550 non-null    object
 42  Days_ShapeAffectedSelfJudgment                 550 non-null    object
 43  Days_DissatisfiedWithWeight                    550 non-null    object
 44  Days_DissatisfiedWithShape                     550 non-null    object
 45  Days_UncomfortableToSeeOwnBody                 550 non-null    object
 46  Days_UncomfortableOthersSeeingYourShape        550 non-null    object
 47  Days_TriedLimitFoodToControlShapeOrWeight      550 non-null    object
 48  Days_FastedToControlShapeOrWeight              550 non-null    object
 49  Days_ExcludedFoodToControlShapeOrWeight        550 non-null    object
 50  Days_FollowedRulesToControlShapeOrWeight       550 non-null    object
 51  Days_FearLosingControlOverEating               550 non-null    object
 52  Eat_SpecificFoodsHabitually                    550 non-null    object
 53  Location_TriggersHabitualEating                550 non-null    object
 54  AutomaticEating_WhenExperiencingStrongEmotion  550 non-null    object
 55  Realize_AfterEatingOutOfHabit                  550 non-null    object
 56  Perception_EatingDisorder                      550 non-null    object
dtypes: object(57)
memory usage: 245.1+ KB

None

=== BEFORE PREPROCESSING: MISSING VALUES ===

Age_Range                                        0
Gender                                           0
Division_ofOrigin                                0
Current_EducationLevel                           0
Employment_Status                                0
Marital_Status                                   0
EatLess_OnWeightGain                             0
EatLess_AtMealtime                               0
RefuseFood_WeightConcern                         0
Monitor_Food                                     0
Eat_SlimmingFoods                                0
EatLess_AfterOvereating                          0
EatLess_ToPreventWeightGain                      0
AvoidSnacks_BetweenMealsForWeightConcern         0
AvoidEveningEating_ForWeightConcern              0
ConsiderWeight_WhenEating                        0
Eat_WhenIrritated                                0
Eat_WhenUnoccupied                               0
Eat_WhenDepressedOrDiscouraged                   0
Eat_WhenLonely                                   0
Eat_WhenSomeoneLetYouDown                        0
Eat_WhenAngry                                    0
Eat_WhenExpectingBad                             0
Eat_WhenAnxious                                  0
Eat_WhenThingsGoWrong                            0
Eat_WhenFrightened                               0
Eat_WhenDisappointed                             0
Eat_WhenEmotionallyUpset                         0
Eat_WhenBoredOrRestless                          0
EatMore_IfFoodTasty                              0
EatMore_IfFoodSmellsOrLooksGood                  0
Eat_WhenSeeDeliciousFood                         0
Eat_DeliciousFoodImmediately                     0
DesireToBuy_FromBakery                           0
DesireToBuy _FromSnackBarOrCafe                  0
DesireToEat_WhenSeeOthersEating                  0
Resist_DeliciousFood                             0
EatMore_WhenSeeOthersEating                      0
Eat_WhenPreparingMeal                            0
Days_DesireForFlatStomach                        0
Days_FeltFat                                     0
Days_WeightAffectedSelfJudgment                  0
Days_ShapeAffectedSelfJudgment                   0
Days_DissatisfiedWithWeight                      0
Days_DissatisfiedWithShape                       0
Days_UncomfortableToSeeOwnBody                   0
Days_UncomfortableOthersSeeingYourShape          0
Days_TriedLimitFoodToControlShapeOrWeight        0
Days_FastedToControlShapeOrWeight                0
Days_ExcludedFoodToControlShapeOrWeight          0
Days_FollowedRulesToControlShapeOrWeight         0
Days_FearLosingControlOverEating                 0
Eat_SpecificFoodsHabitually                      0
Location_TriggersHabitualEating                  0
AutomaticEating_WhenExperiencingStrongEmotion    0
Realize_AfterEatingOutOfHabit                    0
Perception_EatingDisorder                        0
dtype: int64

In [36]:
# -------------------------------------------
# 3A. REMOVE DUPLICATES
# -------------------------------------------
df = df.drop_duplicates()

# -------------------------------------------
# 3B. STRIP SPACES IN ALL TEXT COLUMNS
# -------------------------------------------
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

# -------------------------------------------
# 3C. DEFINE ORDINAL ENCODING DICTIONARIES
# -------------------------------------------

ordinal_map = {
    "Never": 0,
    "Seldom": 1,
    "Sometimes": 2,
    "Often": 3
}

days_map = {
    "No days": 0,
    "1-12 days": 1,
    "13-27 days": 2,
    "Every day": 3
}

target_map = {
    "Yes, I believe I do": 1,
    "No, I don’t believe I do": 0,
    "No, I don't believe I do": 0,
}

# -------------------------------------------
# 3D. APPLY ORDINAL MAPPING TO RELEVANT COLUMNS
# -------------------------------------------

ordinal_cols = [col for col in df.columns if df[col].isin(ordinal_map.keys()).any()]
days_cols = [col for col in df.columns if df[col].isin(days_map.keys()).any()]

for col in ordinal_cols:
    df[col] = df[col].map(ordinal_map)

for col in days_cols:
    df[col] = df[col].map(days_map)

# -------------------------------------------
# 3E. ENCODE TARGET VARIABLE
# -------------------------------------------
df["Perception_EatingDisorder"] = df["Perception_EatingDisorder"].map(target_map)

# -------------------------------------------
# 3F. LABEL ENCODE ANY REMAINING NON-NUMERIC COLUMNS
# -------------------------------------------
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# -------------------------------------------
# 3G. IMPUTE REMAINING MISSING VALUES
# -------------------------------------------
df = df.fillna(df.median(numeric_only=True))

print("\n=== AFTER PREPROCESSING: SAMPLE ROWS ===")
display(df.head())

print("\n=== AFTER PREPROCESSING: INFO ===")
display(df.info())

print("\n=== AFTER PREPROCESSING: SUMMARY STATISTICS ===")
display(df.describe())

print("\n=== CLASS DISTRIBUTION ===")
print(df["Perception_EatingDisorder"].value_counts())

C:\Users\HP\AppData\Local\Temp\ipykernel_15760\2824459617.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

=== AFTER PREPROCESSING: SAMPLE ROWS ===

,Age_Range,Gender,Division_ofOrigin,Current_EducationLevel,Employment_Status,Marital_Status,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,...,Days_TriedLimitFoodToControlShapeOrWeight,Days_FastedToControlShapeOrWeight,Days_ExcludedFoodToControlShapeOrWeight,Days_FollowedRulesToControlShapeOrWeight,Days_FearLosingControlOverEating,Eat_SpecificFoodsHabitually,Location_TriggersHabitualEating,AutomaticEating_WhenExperiencingStrongEmotion,Realize_AfterEatingOutOfHabit,Perception_EatingDisorder
0,0,1,5,2,3,0,3,0,2,2,...,2,3,1,3,1,3,3,2,0,1
1,1,0,1,5,2,1,3,3,1,3,...,1,2,2,0,2,3,2,0,0,1
2,0,1,3,1,3,2,3,0,3,1,...,3,1,1,2,1,0,2,0,0,1
3,0,0,2,1,2,1,3,3,0,2,...,3,1,3,1,1,2,3,3,3,1
4,0,1,7,2,3,2,2,0,1,3,...,1,2,1,1,1,3,3,1,3,1

=== AFTER PREPROCESSING: INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 57 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age_Range                                      550 non-null    int32
 1   Gender                                         550 non-null    int32
 2   Division_ofOrigin                              550 non-null    int32
 3   Current_EducationLevel                         550 non-null    int32
 4   Employment_Status                              550 non-null    int32
 5   Marital_Status                                 550 non-null    int32
 6   EatLess_OnWeightGain                           550 non-null    int64
 7   EatLess_AtMealtime                             550 non-null    int64
 8   RefuseFood_WeightConcern                       550 non-null    int64
 9   Monitor_Food                                   550 non-null    int64
 10  Eat_SlimmingFoods                              550 non-null    int64
 11  EatLess_AfterOvereating                        550 non-null    int64
 12  EatLess_ToPreventWeightGain                    550 non-null    int64
 13  AvoidSnacks_BetweenMealsForWeightConcern       550 non-null    int64
 14  AvoidEveningEating_ForWeightConcern            550 non-null    int64
 15  ConsiderWeight_WhenEating                      550 non-null    int64
 16  Eat_WhenIrritated                              550 non-null    int64
 17  Eat_WhenUnoccupied                             550 non-null    int64
 18  Eat_WhenDepressedOrDiscouraged                 550 non-null    int64
 19  Eat_WhenLonely                                 550 non-null    int64
 20  Eat_WhenSomeoneLetYouDown                      550 non-null    int64
 21  Eat_WhenAngry                                  550 non-null    int64
 22  Eat_WhenExpectingBad                           550 non-null    int64
 23  Eat_WhenAnxious                                550 non-null    int64
 24  Eat_WhenThingsGoWrong                          550 non-null    int64
 25  Eat_WhenFrightened                             550 non-null    int64
 26  Eat_WhenDisappointed                           550 non-null    int64
 27  Eat_WhenEmotionallyUpset                       550 non-null    int64
 28  Eat_WhenBoredOrRestless                        550 non-null    int64
 29  EatMore_IfFoodTasty                            550 non-null    int64
 30  EatMore_IfFoodSmellsOrLooksGood                550 non-null    int64
 31  Eat_WhenSeeDeliciousFood                       550 non-null    int64
 32  Eat_DeliciousFoodImmediately                   550 non-null    int64
 33  DesireToBuy_FromBakery                         550 non-null    int64
 34  DesireToBuy _FromSnackBarOrCafe                550 non-null    int64
 35  DesireToEat_WhenSeeOthersEating                550 non-null    int64
 36  Resist_DeliciousFood                           550 non-null    int64
 37  EatMore_WhenSeeOthersEating                    550 non-null    int64
 38  Eat_WhenPreparingMeal                          550 non-null    int64
 39  Days_DesireForFlatStomach                      550 non-null    int64
 40  Days_FeltFat                                   550 non-null    int64
 41  Days_WeightAffectedSelfJudgment                550 non-null    int64
 42  Days_ShapeAffectedSelfJudgment                 550 non-null    int64
 43  Days_DissatisfiedWithWeight                    550 non-null    int64
 44  Days_DissatisfiedWithShape                     550 non-null    int64
 45  Days_UncomfortableToSeeOwnBody                 550 non-null    int64
 46  Days_UncomfortableOthersSeeingYourShape        550 non-null    int64
 47  Days_TriedLimitFoodToControlShapeOrWeight      550 non-null    int64
 48  Days_FastedToControlShapeOrWeight              550 non-null    int64
 49  Days_ExcludedFoodToControlShapeOrWeight        550 non-null    int64
 50  Days_FollowedRulesToControlShapeOrWeight       550 non-null    int64
 51  Days_FearLosingControlOverEating               550 non-null    int64
 52  Eat_SpecificFoodsHabitually                    550 non-null    int64
 53  Location_TriggersHabitualEating                550 non-null    int64
 54  AutomaticEating_WhenExperiencingStrongEmotion  550 non-null    int64
 55  Realize_AfterEatingOutOfHabit                  550 non-null    int64
 56  Perception_EatingDisorder                      550 non-null    int64
dtypes: int32(6), int64(51)
memory usage: 232.2 KB

None

=== AFTER PREPROCESSING: SUMMARY STATISTICS ===

,Age_Range,Gender,Division_ofOrigin,Current_EducationLevel,Employment_Status,Marital_Status,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,...,Days_TriedLimitFoodToControlShapeOrWeight,Days_FastedToControlShapeOrWeight,Days_ExcludedFoodToControlShapeOrWeight,Days_FollowedRulesToControlShapeOrWeight,Days_FearLosingControlOverEating,Eat_SpecificFoodsHabitually,Location_TriggersHabitualEating,AutomaticEating_WhenExperiencingStrongEmotion,Realize_AfterEatingOutOfHabit,Perception_EatingDisorder
count,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,...,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000
mean,0.352727,0.538182,3.576364,2.412727,1.872727,1.070909,1.776364,1.525455,1.556364,1.561818,...,1.485455,1.387273,1.469091,1.525455,1.454545,1.538182,1.578182,1.481818,1.607273,0.538182
std,0.478254,0.498994,2.326020,1.690707,1.175874,0.825631,1.166856,1.198925,1.133810,1.147896,...,1.089262,1.037117,1.112092,1.063677,1.068137,1.032000,1.047278,1.084178,1.049912,0.498994
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,2.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
50%,0.000000,1.000000,4.000000,2.000000,2.000000,1.000000,2.000000,1.500000,2.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000
75%,1.000000,1.000000,6.000000,4.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000
max,1.000000,1.000000,7.000000,5.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000

=== CLASS DISTRIBUTION ===
Perception_EatingDisorder
1    296
0    254
Name: count, dtype: int64

In [40]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier

# Load dataset
df = pd.read_csv(r"C:\Users\HP\Desktop\FuWukari\Eating Disorder\Dataset.csv")

# -------------------------------
# STEP 1: BASIC CLEANING
# -------------------------------

df = df.drop_duplicates()
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

ordinal_map = {"Never":0, "Seldom":1, "Sometimes":2, "Often":3}
days_map = {"No days":0, "1-12 days":1, "13-27 days":2, "Every day":3}
target_map = {
    "Yes, I believe I do":1,
    "No, I don’t believe I do":0,
    "No, I don't believe I do":0
}

# Map ordinal fields
df = df.replace(ordinal_map)
df = df.replace(days_map)
df["Perception_EatingDisorder"] = df["Perception_EatingDisorder"].replace(target_map)

# Convert remaining non-numeric fields
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

df = df.fillna(0)

# -------------------------------
# STEP 2: FEATURE ENGINEERING
# -------------------------------

# Identify thematic groups based on keyword patterns

restrictive_cols = [
    col for col in df.columns 
    if any(keyword in col for keyword in [
        "EatLess", "RefuseFood", "Avoid", "LimitFood", "Fasted"
    ])
]

emotional_cols = [
    col for col in df.columns 
    if "Eat_When" in col
]

reward_cols = [
    col for col in df.columns 
    if any(keyword in col for keyword in [
        "FoodTasty", "FoodSmells", "DeliciousFood", "DesireToBuy"
    ])
]

habit_cols = [
    col for col in df.columns 
    if any(keyword in col for keyword in [
        "Habit", "SpecificFoods", "AutomaticEating", "OutOfHabit"
    ])
]

body_cols = [
    col for col in df.columns 
    if col.startswith("Days_")
]

demographic_cols = [
    "Age_Range",
    "Gender",
    "Division_ofOrigin",
    "Current_EducationLevel",
    "Employment_Status",
    "Marital_Status"
]

# Create composite psychological scores

df["Restrictive_Eating_Score"] = df[restrictive_cols].mean(axis=1)
df["Emotional_Eating_Score"] = df[emotional_cols].mean(axis=1)

# Reward sensitivity (craving for tasty/attractive food)
reward_related = [
    col for col in df.columns 
    if "Tasty" in col or "Delicious" in col or "Smells" in col or "Desire" in col
]
df["Reward_Sensitivity_Score"] = df[reward_related].mean(axis=1)

df["Habitual_Eating_Score"] = df[habit_cols].mean(axis=1)
df["Body_Image_Distress_Score"] = df[body_cols].mean(axis=1)

# Compress demographic features into one score
df["Demographic_Score"] = df[demographic_cols].mean(axis=1)

# Days disturbance (overall body-image disturbance)
df["Days_Disturbance_Score"] = df[body_cols].sum(axis=1)

# -------------------------------
# STEP 3: SELECT MOST IMPORTANT FEATURES
# -------------------------------

target = "Perception_EatingDisorder"
engineered_features = [
    "Restrictive_Eating_Score",
    "Emotional_Eating_Score",
    "Reward_Sensitivity_Score",
    "Habitual_Eating_Score",
    "Body_Image_Distress_Score",
    "Demographic_Score",
    "Days_Disturbance_Score"
]

X = df[engineered_features]
y = df[target]

# Feature Importance
rf = RandomForestClassifier()
rf.fit(X, y)

importance_df = pd.DataFrame({
    "Feature": engineered_features,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\n=== FEATURE IMPORTANCE ===")
print(importance_df)

# Select top N features
top_features = importance_df["Feature"].head(7).tolist()

print("\n=== FINAL SELECTED FEATURES FOR MODEL ===")
print(top_features)

# -------------------------------
# STEP 4: BUILD FINAL REDUCED DATASET
# -------------------------------

final_df = df[top_features + [target]]

print("\n=== FINAL DATASET PREVIEW ===")
display(final_df.head())

print("\nOriginal Columns:", len(df.columns))
print("Reduced to:", len(final_df.columns)-1, "input features")

C:\Users\HP\AppData\Local\Temp\ipykernel_15760\681878427.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
C:\Users\HP\AppData\Local\Temp\ipykernel_15760\681878427.py:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(ordinal_map)
C:\Users\HP\AppData\Local\Temp\ipykernel_15760\681878427.py:26: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(days_map)
C:\Users\HP\AppData\Local\Temp\ipykernel_15760\681878427.py:27: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Perception_EatingDisorder"] = df["Perception_EatingDisorder"].replace(target_map)

=== FEATURE IMPORTANCE ===
                     Feature  Importance
1     Emotional_Eating_Score    0.258975
0   Restrictive_Eating_Score    0.144512
2   Reward_Sensitivity_Score    0.132141
5          Demographic_Score    0.129870
6     Days_Disturbance_Score    0.117796
4  Body_Image_Distress_Score    0.112421
3      Habitual_Eating_Score    0.104286

=== FINAL SELECTED FEATURES FOR MODEL ===
['Emotional_Eating_Score', 'Restrictive_Eating_Score', 'Reward_Sensitivity_Score', 'Demographic_Score', 'Days_Disturbance_Score', 'Body_Image_Distress_Score', 'Habitual_Eating_Score']

=== FINAL DATASET PREVIEW ===

,Emotional_Eating_Score,Restrictive_Eating_Score,Reward_Sensitivity_Score,Demographic_Score,Days_Disturbance_Score,Body_Image_Distress_Score,Habitual_Eating_Score,Perception_EatingDisorder
0,1.5000,2.000000,1.777778,1.833333,23,1.769231,2.00,1
1,2.1250,2.000000,1.888889,1.666667,15,1.153846,1.25,1
2,2.1250,2.111111,2.222222,1.666667,21,1.615385,0.50,1
3,1.4375,2.222222,1.888889,1.000000,18,1.384615,2.75,1
4,1.3125,2.000000,1.777778,2.500000,17,1.307692,2.50,1

Original Columns: 64
Reduced to: 7 input features

In [42]:
# -----------------------------------------------------
# SAVE CLEANED FULL DATASET (AFTER CLEANING + ENCODING)
# -----------------------------------------------------
df.to_csv("Cleaned_Full_Data.csv", index=False)
print("Saved: Cleaned_Full_Data.csv")

# -----------------------------------------------------
# GET REDUCED FEATURE SET + TARGET
# -----------------------------------------------------
final_df = df[top_features + ["Perception_EatingDisorder"]]

# Save reduced engineered dataset
final_df.to_csv("Engineered_Reduced_Data.csv", index=False)
print("Saved: Engineered_Reduced_Data.csv")

# -----------------------------------------------------
# TRAIN-TEST SPLIT (80/20 WITH STRATIFICATION)
# -----------------------------------------------------
from sklearn.model_selection import train_test_split

X = final_df.drop("Perception_EatingDisorder", axis=1)
y = final_df["Perception_EatingDisorder"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.20, 
    random_state=42, 
    stratify=y
)

# -----------------------------------------------------
# SAVE SPLIT DATASETS
# -----------------------------------------------------
X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

print("Saved all train/test split files.")
print("\nTrain shape:", X_train.shape)
print("Test shape:", X_test.shape)

Saved: Cleaned_Full_Data.csv
Saved: Engineered_Reduced_Data.csv
Saved all train/test split files.

Train shape: (440, 7)
Test shape: (110, 7)

In [80]:
# ============================================================
# 1. IMPORTS
# ============================================================
import pandas as pd
import numpy as np
import os
import joblib

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.models import Model

# ============================================================
# 2. LOAD DATASET
# ============================================================
df = pd.read_csv(r"C:\Users\HP\Desktop\FuWukari\Eating Disorder\Dataset.csv")
print("Raw Loaded Dataset:", df.shape)

df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

# ============================================================
# 3. MAP RESPONSES → NUMBERS
# ============================================================
ordinal_map = {"Never": 0, "Seldom": 1, "Sometimes": 2, "Often": 3}
days_map = {"No days": 0, "1-12 days": 1, "13-27 days": 2, "Every day": 3}
binary_map = {
    "Yes, I believe I do": 1,
    "No, I don’t believe I do": 0,
    "No, I don't believe I do": 0
}

df = df.replace(ordinal_map)
df = df.replace(days_map)
df["Perception_EatingDisorder"] = df["Perception_EatingDisorder"].replace(binary_map)

# ============================================================
# 4. FEATURE ENGINEERING (7 FEATURES)
# ============================================================
restrict_cols = [c for c in df.columns if "EatLess" in c or "Avoid" in c]
emotional_cols = [c for c in df.columns if "Eat_When" in c]
reward_cols = [c for c in df.columns if "Food" in c and "Eat_When" not in c]
habit_cols = [c for c in df.columns if "Habit" in c or "Automatic" in c]
body_cols = [c for c in df.columns if "Days_" in c]

df["Restrictive_Eating_Score"] = df[restrict_cols].mean(axis=1)
df["Emotional_Eating_Score"] = df[emotional_cols].mean(axis=1)
df["Reward_Sensitivity_Score"] = df[reward_cols].mean(axis=1)
df["Habitual_Eating_Score"] = df[habit_cols].mean(axis=1)
df["Body_Image_Distress_Score"] = df[body_cols].mean(axis=1)

df["ED_Risk_Score"] = df[
    [
        "Restrictive_Eating_Score",
        "Emotional_Eating_Score",
        "Reward_Sensitivity_Score",
        "Habitual_Eating_Score",
        "Body_Image_Distress_Score"
    ]
].mean(axis=1)

# Demographics
demo_cols = [
    "Age_Range", "Gender", "Division_ofOrigin",
    "Current_EducationLevel", "Employment_Status", "Marital_Status"
]

print("\nDemographic Columns Found:", demo_cols)

for col in demo_cols:
    df[col] = LabelEncoder().fit_transform(df[col])

df["Demographic_Score"] = df[demo_cols].mean(axis=1)

# ============================================================
# 5. CLINICAL TARGET LABEL
# ============================================================
df["ED_Risk_Label"] = (df["ED_Risk_Score"] >= 2.0).astype(int)
print("\nED Risk Label Counts:\n", df["ED_Risk_Label"].value_counts())

# ============================================================
# 6. FINAL FEATURE SET
# ============================================================
final_df = df[
    [
        "Restrictive_Eating_Score",
        "Emotional_Eating_Score",
        "Reward_Sensitivity_Score",
        "Habitual_Eating_Score",
        "Body_Image_Distress_Score",
        "ED_Risk_Score",
        "Demographic_Score",
        "ED_Risk_Label"
    ]
]

print("\nFinal Engineered Dataset:", final_df.shape)

# ============================================================
# 7. SCALING + SMOTE
# ============================================================
X = final_df.drop("ED_Risk_Label", axis=1)
y = final_df["ED_Risk_Label"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X_scaled, y)

print("\nAfter SMOTE:", X_res.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res, test_size=0.2, random_state=42, stratify=y_res
)

# ============================================================
# 8. MODEL TRAINING
# ============================================================
inputs = Input(shape=(7,))
x = Dense(32, activation="relu")(inputs)
x = Dense(16, activation="relu")(x)
x = Dropout(0.2)(x)
outputs = Dense(1, activation="sigmoid")(x)

model = Model(inputs, outputs)
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=40,
    batch_size=32,
    verbose=1
)

# ============================================================
# 9. EVALUATION
# ============================================================
y_pred = (model.predict(X_test) > 0.5).astype(int)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, model.predict(X_test))
cm = confusion_matrix(y_test, y_pred)

print("\nACCURACY:", acc)
print("PRECISION:", prec)
print("RECALL:", rec)
print("F1 SCORE:", f1)
print("AUC:", auc)
print("\nCONFUSION MATRIX:\n", cm)

# ============================================================
# 10. SAVE MODEL + SCALER AUTOMATICALLY
# ============================================================
save_path = r"C:\Users\HP\Desktop\FuWukari\Eating Disorder"
os.makedirs(save_path, exist_ok=True)

model.save(os.path.join(save_path, "ed_risk_model.h5"))
joblib.dump(scaler, os.path.join(save_path, "ed_scaler.pkl"))

print("\n✔ Model & Scaler Saved Successfully!")
print("Saved to:", save_path)

Raw Loaded Dataset: (550, 57)

Demographic Columns Found: ['Age_Range', 'Gender', 'Division_ofOrigin', 'Current_EducationLevel', 'Employment_Status', 'Marital_Status']

ED Risk Label Counts:
 ED_Risk_Label
0    540
1     10
Name: count, dtype: int64

Final Engineered Dataset: (550, 8)

After SMOTE: (1080, 7)
Epoch 1/40

C:\Users\HP\AppData\Local\Temp\ipykernel_15760\3449932138.py:25: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
C:\Users\HP\AppData\Local\Temp\ipykernel_15760\3449932138.py:38: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(ordinal_map)
C:\Users\HP\AppData\Local\Temp\ipykernel_15760\3449932138.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(days_map)
C:\Users\HP\AppData\Local\Temp\ipykernel_15760\3449932138.py:40: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Perception_EatingDisorder"] = df["Perception_EatingDisorder"].replace(binary_map)

22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.6252 - loss: 0.6593 - val_accuracy: 0.8555 - val_loss: 0.5585
Epoch 2/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8278 - loss: 0.5022 - val_accuracy: 0.9017 - val_loss: 0.4349
Epoch 3/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8799 - loss: 0.4022 - val_accuracy: 0.9191 - val_loss: 0.3354
Epoch 4/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9117 - loss: 0.3263 - val_accuracy: 0.9538 - val_loss: 0.2618
Epoch 5/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9378 - loss: 0.2591 - val_accuracy: 0.9538 - val_loss: 0.2060
Epoch 6/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9421 - loss: 0.2211 - val_accuracy: 0.9595 - val_loss: 0.1659
Epoch 7/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9465 - loss: 0.1952 - val_accuracy: 0.9595 - val_loss: 0.1354
Epoch 8/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9551 - loss: 0.1552 - val_accuracy: 0.9711 - val_loss: 0.1122
Epoch 9/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9682 - loss: 0.1228 - val_accuracy: 0.9711 - val_loss: 0.0949
Epoch 10/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9638 - loss: 0.1152 - val_accuracy: 0.9769 - val_loss: 0.0808
Epoch 11/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9653 - loss: 0.1034 - val_accuracy: 0.9827 - val_loss: 0.0700
Epoch 12/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9783 - loss: 0.0859 - val_accuracy: 0.9769 - val_loss: 0.0629
Epoch 13/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9841 - loss: 0.0743 - val_accuracy: 0.9769 - val_loss: 0.0566
Epoch 14/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9812 - loss: 0.0745 - val_accuracy: 0.9769 - val_loss: 0.0510
Epoch 15/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9812 - loss: 0.0713 - val_accuracy: 0.9884 - val_loss: 0.0456
Epoch 16/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9855 - loss: 0.0626 - val_accuracy: 0.9827 - val_loss: 0.0430
Epoch 17/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9841 - loss: 0.0585 - val_accuracy: 0.9884 - val_loss: 0.0385
Epoch 18/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9841 - loss: 0.0570 - val_accuracy: 0.9884 - val_loss: 0.0352
Epoch 19/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9928 - loss: 0.0504 - val_accuracy: 0.9884 - val_loss: 0.0343
Epoch 20/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0429 - val_accuracy: 0.9884 - val_loss: 0.0310
Epoch 21/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9884 - loss: 0.0421 - val_accuracy: 0.9827 - val_loss: 0.0298
Epoch 22/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9913 - loss: 0.0367 - val_accuracy: 0.9942 - val_loss: 0.0262
Epoch 23/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9841 - loss: 0.0494 - val_accuracy: 0.9942 - val_loss: 0.0252
Epoch 24/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9942 - loss: 0.0303 - val_accuracy: 0.9942 - val_loss: 0.0244
Epoch 25/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9913 - loss: 0.0371 - val_accuracy: 0.9942 - val_loss: 0.0231
Epoch 26/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9928 - loss: 0.0312 - val_accuracy: 0.9942 - val_loss: 0.0224
Epoch 27/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9928 - loss: 0.0276 - val_accuracy: 0.9942 - val_loss: 0.0204
Epoch 28/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9899 - loss: 0.0301 - val_accuracy: 0.9942 - val_loss: 0.0194
Epoch 29/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9942 - loss: 0.0246 - val_accuracy: 0.9942 - val_loss: 0.0195
Epoch 30/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9942 - loss: 0.0216 - val_accuracy: 0.9942 - val_loss: 0.0187
Epoch 31/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9957 - loss: 0.0225 - val_accuracy: 0.9884 - val_loss: 0.0191
Epoch 32/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9928 - loss: 0.0243 - val_accuracy: 0.9942 - val_loss: 0.0173
Epoch 33/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9957 - loss: 0.0244 - val_accuracy: 0.9884 - val_loss: 0.0184
Epoch 34/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9928 - loss: 0.0239 - val_accuracy: 0.9884 - val_loss: 0.0174
Epoch 35/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9928 - loss: 0.0199 - val_accuracy: 0.9942 - val_loss: 0.0141
Epoch 36/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9971 - loss: 0.0179 - val_accuracy: 0.9942 - val_loss: 0.0142
Epoch 37/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9913 - loss: 0.0209 - val_accuracy: 0.9942 - val_loss: 0.0140
Epoch 38/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9942 - loss: 0.0165 - val_accuracy: 0.9942 - val_loss: 0.0143
Epoch 39/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9942 - loss: 0.0157 - val_accuracy: 0.9884 - val_loss: 0.0152
Epoch 40/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9942 - loss: 0.0199 - val_accuracy: 0.9884 - val_loss: 0.0157
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

ACCURACY: 0.9953703703703703
PRECISION: 0.9908256880733946
RECALL: 1.0
F1 SCORE: 0.9953917050691244
AUC: 1.0

CONFUSION MATRIX:
 [[107   1]
 [  0 108]]

✔ Model & Scaler Saved Successfully!
Saved to: C:\Users\HP\Desktop\FuWukari\Eating Disorder